---
title: "p8105_hw4_wl2632"
author: "Weijie Liu"
date: "October 27, 2017"
output: html_document
---

## Problem 1

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(haven)
library(rvest)
library(stringr)
library(forcats)

pups_data = read.csv(file = "./data/FAS_pups.csv") %>%
  clean_names() %>%
  gather(key = PD_outcome, value = days, pd_ears:pd_walk) %>%
  mutate(sex = str_replace(sex, "1", "male"),
         sex = str_replace(sex, "2", "female")) %>%
  filter(!is.na(days))
  
  
```

* The collaborator will create a plot showing the distribution of post-natal days for each developmental landmark. (pj2325)
```{r}
<<<<<<< HEAD
pups_data %>% 
  group_by(PD_outcome) %>% 
  ggplot(aes(x = litter_number, y = days, color = PD_outcome)) +
  geom_point(alpha = .4) +
  facet_grid(. ~PD_outcome)


=======
pups_tidy_data %>% 
  ggplot(aes(y = PD_outcome, x = days, color = PD_outcome)) +
  geom_density_ridges(scale = 0.7) + labs(title = "Distribution of Post-natal Days for Each Developmental Landmark", x = "Days", y = "PD_Landmarks")
>>>>>>> 9dedb2a1f5af3db7c6c9df58839188f0522fdc31
```




